version: '3'
services:
  mycontainer:
    image: ubuntu:latest
    tty: true
    container_name: mycontainer
    command: tail -f /dev/null
    volumes:
      - ./pastausr1:/home/user1/pastausr1
      - ./pastausr2:/home/user2/pastausr2
    cap_add:
      - SYS_ADMIN
    privileged: true
    devices:
      - /dev/fuse
    entrypoint: /bin/bash -c "useradd -m user1 && useradd -m user2 && echo 'olá user1' > /home/user1/pastausr1/texto.txt && echo 'olá user2' > /home/user2/pastausr2/texto.txt && chown user1:user1 /home/user1/pastausr1/texto.txt && chmod 644 /home/user1/pastausr1/texto.txt && chmod 755 /home/user1"
